### ISSUE TITLE
badge.

### ISSUE THREAD

**Issue by jihunkang21** [KimDarren/UIButton-Hit#1]
https://github.com/badges/cocoapod-badges
Please apply this badge.

**Comment by KimDarren** [comment]
Fuck you. Suck my dick :dancers:

**Comment by KimDarren** [comment]
You are liar haha

**Comment by jihunkang21** [comment]
what the f

**Comment by KimDarren** [comment]
That's what i'm doing now

**Comment by jihunkang21** [comment]
thank you.

**Comment by KimDarren** [comment]
Okay, I'm done!
You should check it in the [README.md](https://github.com/KimDarren/UIButton-Hit/blob/master/README.md)
thx
